#!/bin/bash -l
#SBATCH --time=001:29:00
#SBATCH --job-name=3d_wall_loads
#SBATCH --exclusive
#SBATCH --exclude=c07n128 
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=56
#SBATCH --nodes=1
#SBATCH --partition=gen11
#SBATCH --error myjob.err

export OMP_NUM_THREADS=56
export SLURM_CPU_BIND="rank"   # It does not seem to affect anything

ifort -qopenmp -o analyze_wall_T /home/ITER/artolaj/scripts_hub/scripts_javier/tasks/heat_load_analysis/analyze_wall_T.f90 
./analyze_wall_T > output_analyze_T
