#!/bin/bash -l
#SBATCH --time=000:29:00
#SBATCH --job-name=3d_wall_loads
#SBATCH --exclusive
#SBATCH --exclude=c07n128 
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=56
#SBATCH --nodes=1
#SBATCH --partition=gen11_debug
#SBATCH --error myjob.err

export OMP_NUM_THREADS=56
export SLURM_CPU_BIND="rank"   # It does not seem to affect anything

# Define the start and end indices
i_start=00000  # Replace with your actual start index
i_end=200000    # Replace with your actual end index
i_jump=100     # Jump these restart files

# inputs
jorek_exec="$HOME/git.jorek2/fluid_loads_on_3D_wall"
jorek_input="./input"
wall_f_name="mush0_"
namelist_file="heat_load.nml"
output_dir="./output_load_vtks"

# Create output directory if it doesn't exist
mkdir -p "$output_dir"

# Export namelist
cat > "$output_dir/$namelist_file" << EOF
&restart_inputs
  i_begin       = $i_start,
  i_jump_steps  = $i_jump,
  i_end         = $i_end,
  wall_f_name   = "$wall_f_name"
/
EOF

# Directory containing the files
directory="."  # Replace with your actual directory path
lockfile="./mylockfile.lock"

# Loop from i_start to i_end
for ((i=i_start; i<=i_end; i+=i_jump)); do
    # Format the filename with leading zeros if necessary
    filename=$(printf "jorek%06d.h5" $i)

    # Full path to the original file
    original_file="${directory}/${filename}"

    # Full path to the new file
    new_file="${directory}/jorek_restart.h5"

    # Check if the original file exists
    if [[ -e $original_file ]]; then
        # Rename the file
        exec 200>"$lockfile"
	flock -n 200 || { echo "Failed to acquire lock"; exit 1; }

        cp "$original_file" "$new_file"

	flock -u 200
        exec 200>&-  # Close file descriptor 200

        echo "Copied $original_file to $new_file"
        echo "Run wall_wetted area"
        srun "$jorek_exec" < "$jorek_input" > out_loads

	exec 200>"$lockfile"
	flock -n 200 || { echo "Failed to acquire lock"; exit 1; }

        wetted_vtk=$(printf "%s%06d.vtk" "$wall_f_name" "$i")
        mv "3D_wall_fluid_loads.vtk" "$output_dir/$wetted_vtk"
        
	flock -u 200
        exec 200>&-  # Close file descriptor 200
    else
        echo "File not found: $original_file"
    fi
done
